---
- name: Gather info from Linux Template
  vmware_guest_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vsphere_datacenter }}'
    name: '{{ lin_temp }}'
    validate_certs: 'no'
  delegate_to: localhost
  register: wdc_info

- name: Removing snapshots for webservers
  vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vsphere_datacenter }}"
    folder: "{{ wdc_info['instance']['hw_folder'] }}"
    name: "{{ inventory_hostname }}"
    validate_certs: 'no'
    state: absent
    snapshot_name: snap001
  delegate_to: localhost
  register: result
